### PR TITLE
Corrected minor spelling mistakes and grammar.

### PR DESCRIPTION
**Pull request by IttayWeiss**

### CODE REVIEW

**Comment by mrthankyou** [comment]
@IttayWeiss 

It looks like that `ch-prerequisites/python-and-jupyter-notebooks.ipynb` has a conflicting file change. Can you resolve the conflict? Alternatively, I can take if off your hands and submit a new PR with the fix you suggested here. Thanks.

**Comment by IttayWeiss** [comment]
@mrthankyou 

Thanks for your comment. I don't know how to resolve the conflict. The 'resolve conflict' button is greyed out. I would like to learn how to do it though, so any suggestions would be welcomed. Should I remove this PR and create a new one? Many thanks.

**Comment by mrthankyou** [comment]
Hmm that stinks. We have two solutions then:

1. Remove this PR and create a new PR with your changes. 
2. Using git, you can resolve the conflict on your local machine and push the new changes to this PR. See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line) for more info.

If you've never done option 2 before, option 1 will likely be easier for you. If you need any further help let me know.

**Comment by IttayWeiss** [comment]
@mrthankyou 
I'll remove this one and try again. 

Thank you!

**Pull request closed without merging**
