### PR TITLE
Improve 1.3

### PR DESCRIPTION
**Pull request by quantumjim**
Some improvements to part 1 so far. This restored some good parts of sections that have been removed, and addressed some of the comments in issue #395 .

To do:
* address the other comments
* maybe remove the Bloch sphere?

### CODE REVIEW

**Comment by nonhermitian** [comment]
> If you are not familiar with vectors, you can essentially just think of them as lists of numbers which we manipulate using certain rules. 

We have linear algebra as a prerequisite and go over vectors in that section, so should assume the reader knows this information.

> This is a lot of notation to take in all at once. First let's unpack the weird $|$ and $\rangle$ 

This is not weird, but may be unfamiliar to the reader.  However, again, linear algebra is a prerequisite, and this notation is used there.

> If you are not familiar with vectors, you can essentially just think of them as lists of numbers which we manipulate using certain rules. 

Same.

> For example, thebvelocity

Spelling

> If you are familiar with vectors from your high school physics classes, you'll know that these rules make vectors well-suited for describing quantities with a magnitude and a direction. For example, thebvelocity of an object is described perfectly with a vector. However, the way we use vectors for quantum states is slightly different to this. 

The vectors in QM also have amplitudes and directions.

This chapter highlights a general disconnect between the linear algebra "prerequisite" and the text.  A prerequisite is something that is necessary to have ahead of time.  Thus we should either assume that the reader knows it, or drop the notion of linear algebra as a prerequisite, and move it to an appendix.

**Comment by quantumjim** [comment]
Thanks for the comments. But regarding the 'linear algebra as a prerequisite' thing, I don't think reading a wall of text on linear algebra should be a prerequisite. It is better for us to introduce as we go along, and refer to the lin alg section as a resource that can be used for people to brush up.

**Comment by quantumjim** [comment]
There is a lot that people can get out of the textbook without needing to stare at the Maclaurin series, etc. What's the point in trying to start the textbook off in a gentle and ped

**Comment by nonhermitian** [comment]
I would agree.  The lin alg section is quite overwhelming.  But it does mean a decision about readers knowledge level needs to be solidified.  I see you are doing this in #409

**Comment by quantumjim** [comment]
Since the improving the Bloch sphere part is dependent on a Terra PR (for alternative measurements). We can do that in a future PR. I've taken the WIP off for now.

I haven't merged myself, because I don't like overusing my superpowers.

**Comment by frankharkins** [comment]
This is much better, thanks @quantumjim.

**Pull request merged**
