### PR TITLE
Fixes for #104 #346 #353

### LINKED ISSUE #104: Error in Chapter 2.5 "Proving Universality"
In this section of the textbook it says:

> We know how to create the unitary $e^{i\frac{\theta}{2} X\otimes X\otimes X}$ from a single qubit $R_x(\theta)$ and two controlled-NOTs.

```python
qc.cx(0,2)
qc.cx(0,1)
qc.rx(theta,0)
qc.cx(0,1)
qc.cx(0,1)
```

>With a few Hadamards, we can do the same for $e^{i\frac{\theta}{2} Z\otimes Z\otimes Z}$.

```python
qc.h(0)
qc.h(1)
qc.h(2)
qc.cx(0,2)
qc.cx(0,1)
qc.rx(theta,0)
qc.cx(0,1)
qc.cx(0,1)
qc.h(2)
qc.h(1)
qc.h(0)
```
For a correct implementation of these transformations I think that one CNOT gate must be applied to the qubit "2" for a symmetric transformation, the implementations must be as follows 
```python
qc.cx(0,2)
qc.cx(0,1)
qc.rx(theta,0)
qc.cx(0,1)
**qc.cx(0,2)** #change qc.cx(0,1) by qc.cx(0,2)
```
and 

```python
qc.h(0)
qc.h(1)
qc.h(2)
qc.cx(0,2)
qc.cx(0,1)
qc.rx(theta,0)
qc.cx(0,1)
**qc.cx(0,2)**  #change qc.cx(0,1) by qc.cx(0,2)
qc.h(2)
qc.h(1)
qc.h(0)
```
Best regards :)

### LINKED ISSUE #346: Two corrections : It should have a sign "-" plus a typo on a CNOT gate
In this chapter.
https://qiskit.org/textbook/ch-gates/proving-universality.html

Maybe two corrections to make:

1) The exponential exp(iθ/2 X⊗X⊗X) should be exp(-iθ/2 X⊗X⊗X) : there should be a negative sign for the angle, if the rotation Rx(θ)  has the same matrix in https://qiskit.org/documentation/stubs/qiskit.extensions.RXGate.html

2) At the same time, in the corresponding circuit, the last CNOT gate should be qc.cx(0,2) instead of qc.cx(0,1).

This is the reason:

exp(iθ/2 X⊗X⊗X) = cos(θ/2)I + isin(θ/2) X⊗X⊗X, the matrix is
cos(θ/2)	0	0	0	0	0	0	isin(θ/2)
0	cos(θ/2)	0	0	0	0	isin(θ/2)	0
0	0	cos(θ/2)	0	0	isin(θ/2)	0	0
0	0	0	cos(θ/2)	isin(θ/2)	0	0	0
0	0	0	isin(θ/2)	cos(θ/2)	0	0	0
0	0	isin(θ/2)	0	0	cos(θ/2)	0	0
0	isin(θ/2)	0	0	0	0	cos(θ/2)	0
isin(θ/2)	0	0	0	0	0	0	cos(θ/2)	

When the input is |000>, the (corrected) circuit outputs cos(θ/2)|000> -  isin(θ/2)|111> or the vector [cos(θ/2),0,0,0,0,0,0,-isin(θ/2)], but exp(iθ/2 X⊗X⊗X) gives the vector using the matrix : [cos(θ/2),0,0,0,0,0,0,isin(θ/2)].
There are identical except a “-“ sign before isin(θ/2), so if exp(-iθ/2 X⊗X⊗X) it should be OK.

### LINKED ISSUE #353: 5.1 typo in "The basics of error correction" paragraph
## Describe the Issue
One instance of "classical information" should be "quantum information" . 
> The basics of error correction 
> The basic ideas behind error correction are the same for classical information as for classical information. 
>

### PR DESCRIPTION
**Pull request by aditya-giri**
This fixes #104, fixes #346 and fixes #353

### CODE REVIEW

**Comment by aditya-giri** [comment]
@frankharkins @1ucian0 would you mind taking a quick look? Also at this PR: #358.They're quite small.

**Comment by frankharkins** [comment]
This is great, I will need a pen and paper to verify #346 but I will merge as soon as I do. Thanks @aditya-giri

**Comment by aditya-giri** [comment]
Sure, thank you @frankharkins

**Comment by frankharkins** [comment]
looks good, thank you!

**Pull request merged**
